name: hello-actions

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Print message
        run: echo "Hello GitHub Actions in ${{ Vars.MY_ENV }}"
   
  build:
    runs-on: ubuntu-latest
    environment: Development
    needs: hello
    steps:
      - name: build something
        run: echo "build the hello in ${{ Vars.MY_ENV }}"

  market:
    runs-on: ubuntu-latest
    steps:
      - name: hello JS
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Vlad
  
  slacknotif:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: Done yo!
